export const PHOTO_CATEGORIES = [
  "Aft Cabin",
  "Aft Deck",
  "Beach Club",
  "Bow",
  "Cabin",
  "Captain's Stateroom",
  "Captain's Stateroom Head",
  "Cockpit",
  "Command Deck",
  "Companionway",
  "Console",
  "Crew",
  "Crew Stateroom",
  "Crew Stateroom Head",
  "Day Head",
  "Dinette",
  "Electrical Room",
  "Enclosed Flybridge",
  "Enclosed Flybridge Aft Deck",
  "Engine Room",
  "Engines",
  "Flybridge",
  "Forward Stateroom",
  "Forward Stateroom Head",
  "Foyer",
  "Fwd Port Guest Stateroom",
  "Fwd Port Guest Stateroom Head",
  "Fwd Starboard Guest Stateroom",
  "Fwd Starboard Guest Stateroom Head",
  "Galley",
  "Generator Room",
  "Guest Stateroom",
  "Guest Stateroom Head",
  "Head",
  "Helm",
  "Laundry",
  "Lazarette",
  "Lower Companionway",
  "Lower Foyer",
  "Main Deck Foyer",
  "Master Stateroom",
  "Master Stateroom Head",
  "Mechanical Room",
  "Mid Port Guest Stateroom",
  "Mid Port Guest Stateroom Head",
  "Mid Starboard Guest Stateroom",
  "Mid Starboard Guest Stateroom Head",
  "On Deck Master Stateroom",
  "On Deck Master Stateroom Head",
  "Pantry",
  "Pilothouse",
  "Port",
  "Port Guest Stateroom",
  "Port Guest Stateroom Head",
  "Port Passageway",
  "Profiles",
  "Salon",
  "Skylounge",
  "Skylounge Aft Deck",
  "Skylounge Day Head",
  "Starboard",
  "Starboard Guest Stateroom",
  "Starboard Guest Stateroom Head",
  "Starboard Passageway",
  "Stern",
  "Sun Deck",
  "Swim Platform",
  "Tower",
  "VIP Stateroom",
  "VIP Stateroom Head",
  "Other",
] as const;
